"""creating gif column

Revision ID: 036d86a317d3
Revises: 74c99d75b1aa
Create Date: 2026-01-03 13:17:33.333060

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "036d86a317d3"
down_revision = "74c99d75b1aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gif", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_column("gif")

    # ### end Alembic commands ###
