"""empty message

Revision ID: 130574b8cd10
Revises: 834d6bea1714
Create Date: 2025-11-11 12:26:54.999184

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "130574b8cd10"
down_revision = "834d6bea1714"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_premium", sa.Boolean(), nullable=True))
        batch_op.alter_column(
            "email_token",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=10),
            existing_nullable=True,
        )
        batch_op.drop_column("premium_membership")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "premium_membership", sa.BOOLEAN(), autoincrement=False, nullable=True
            )
        )
        batch_op.alter_column(
            "email_token",
            existing_type=sa.String(length=10),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True,
        )
        batch_op.drop_column("is_premium")

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    # ### end Alembic commands ###
