"""static ads

Revision ID: 13fe2b08236b
Revises: 8da63451d27b
Create Date: 2026-01-22 14:56:22.870382

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13fe2b08236b"
down_revision = "8da63451d27b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ad_campaigns", schema=None) as batch_op:
        batch_op.add_column(sa.Column("placement", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ad_campaigns", schema=None) as batch_op:
        batch_op.drop_column("placement")

    # ### end Alembic commands ###
