"""empty message

Revision ID: 3a2cd6c6fdec
Revises: a43ee5c3069f
Create Date: 2025-11-17 16:37:28.978818

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a2cd6c6fdec"
down_revision = "a43ee5c3069f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("max_impressions", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("features", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ad_campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image", sa.String(length=500), nullable=True),
        sa.Column("target_url", sa.String(length=500), nullable=True),
        sa.Column("call_to_action", sa.String(length=50), nullable=True),
        sa.Column("target_audience", sa.String(length=50), nullable=True),
        sa.Column("target_countries", sa.Text(), nullable=True),
        sa.Column("target_interests", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("budget", sa.Float(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("click_through_rate", sa.Float(), nullable=True),
        sa.Column("payment_status", sa.String(length=20), nullable=True),
        sa.Column("payment_gateway", sa.String(length=20), nullable=True),
        sa.Column("payment_id", sa.String(length=255), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["ad_packages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payment_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("gateway", sa.String(length=20), nullable=False),
        sa.Column("gateway_payment_id", sa.String(length=255), nullable=True),
        sa.Column("gateway_status", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("gateway_metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["ad_campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reactions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("reactions_post_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("reactions_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "users", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "posts", ["post_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    with op.batch_alter_table("reactions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("reactions_user_id_fkey"), "users", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("reactions_post_id_fkey"), "posts", ["post_id"], ["id"]
        )

    op.drop_table("payment_transactions")
    op.drop_table("ad_campaigns")
    op.drop_table("ad_packages")
    # ### end Alembic commands ###
