"""add password reset fields

Revision ID: 413fddaabe53
Revises: 00b27f21e7a2
Create Date: 2025-11-21 07:04:27.983753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413fddaabe53'
down_revision = '00b27f21e7a2'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('ad_campaigns') as batch_op:
        # 1. allow NULL first
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiry_notification_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_renew', sa.Boolean(), nullable=True))

    # 2. populate values for existing rows
    op.execute("UPDATE ad_campaigns SET duration_days = 7 WHERE duration_days IS NULL")
    
    # 3. now make duration_days required
    with op.batch_alter_table('ad_campaigns') as batch_op:
        batch_op.alter_column('duration_days', nullable=False)

    # 4. NOW drop old columns + constraint
    with op.batch_alter_table('ad_campaigns') as batch_op:
        batch_op.drop_constraint(batch_op.f('ad_campaigns_package_id_fkey'), type_='foreignkey')
        batch_op.drop_column('target_audience')
        batch_op.drop_column('package_id')
        batch_op.drop_column('target_interests')
        batch_op.drop_column('target_countries')

    # 5. create unique constraint — but safely!
    with op.batch_alter_table('user_blocks') as batch_op:
        # batch_op.create_unique_constraint(
            # 'uq_user_block',
            # ['blocker_id', 'blocked_id']
        # )
        pass


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_reset_expires')
        batch_op.drop_column('password_reset_token')

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_block', type_='unique')

    # ### end Alembic commands ###
