"""old

Revision ID: 46f183175e71
Revises: 1dddcb7b0b21
Create Date: 2025-11-25 15:46:52.579302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f183175e71'
down_revision = '1dddcb7b0b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_devices', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_platforms', sa.Text(), nullable=True))

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_block', type_='unique')

    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.drop_column('target_platforms')
        batch_op.drop_column('target_devices')
        batch_op.drop_column('target_language')

    # ### end Alembic commands ###
