"""added location

Revision ID: 4e6c0a484dff
Revises: 90a4f5e6a01a
Create Date: 2026-01-28 09:54:15.831051

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e6c0a484dff"
down_revision = "90a4f5e6a01a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_column("location")

    # ### end Alembic commands ###
