"""first migration

Revision ID: 55b2bc8530f6
Revises: 6f3e0c7087bb
Create Date: 2025-11-18 11:17:30.415320

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55b2bc8530f6"
down_revision = "6f3e0c7087bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    # ### end Alembic commands ###
