"""migffffff

Revision ID: 577b66b2d3e4
Revises: c30f592bf05c
Create Date: 2025-11-27 17:29:07.593254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577b66b2d3e4'
down_revision = 'c30f592bf05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchmaking_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('matchmaking_requests_payment_transaction_id_fkey'), type_='foreignkey')
        batch_op.drop_column('payment_transaction_id')

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('gateway',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('gateway_reference',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('gateway_payment_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['gateway_reference'])
        batch_op.drop_constraint(batch_op.f('payment_transactions_ad_campaign_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ad_campaigns', ['campaign_id'], ['id'])
        batch_op.drop_column('ad_campaign_id')

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
       #  batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
       pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_block', type_='unique')

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_campaign_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payment_transactions_ad_campaign_id_fkey'), 'ad_campaigns', ['ad_campaign_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('gateway_payment_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('gateway_reference',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('gateway',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('campaign_id')

    with op.batch_alter_table('matchmaking_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('matchmaking_requests_payment_transaction_id_fkey'), 'payment_transactions', ['payment_transaction_id'], ['id'])

    # ### end Alembic commands ###
