"""innndddd

Revision ID: 64a94d48c3a9
Revises: 6ca5dceeefd5
Create Date: 2025-12-08 01:50:52.540165

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "64a94d48c3a9"
down_revision = "6ca5dceeefd5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index("idx_notifications_actor_id", ["actor_id"], unique=False)
        batch_op.create_index(
            "idx_notifications_created_at", ["created_at"], unique=False
        )
        batch_op.create_index("idx_notifications_is_read", ["is_read"], unique=False)
        batch_op.create_index("idx_notifications_type", ["type"], unique=False)
        batch_op.create_index("idx_notifications_user_id", ["user_id"], unique=False)
        batch_op.create_index(
            "idx_notifications_user_unread",
            ["user_id", "is_read", "created_at"],
            unique=False,
        )

    op.drop_table("notification")
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.create_index("idx_comments_author_id", ["author_id"], unique=False)
        batch_op.create_index(
            "idx_comments_author_post", ["author_id", "post_id"], unique=False
        )
        batch_op.create_index("idx_comments_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_comments_parent_id", ["parent_id"], unique=False)
        batch_op.create_index(
            "idx_comments_post_created", ["post_id", "created_at"], unique=False
        )
        batch_op.create_index("idx_comments_post_id", ["post_id"], unique=False)

    with op.batch_alter_table("marketplace_services", schema=None) as batch_op:
        batch_op.create_index("idx_services_category_id", ["category_id"], unique=False)
        batch_op.create_index(
            "idx_services_category_status", ["category_id", "status"], unique=False
        )
        batch_op.create_index("idx_services_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            "idx_services_description_trgm",
            ["description"],
            unique=False,
            postgresql_using="gin",
            postgresql_ops={"description": "gin_trgm_ops"},
        )
        batch_op.create_index(
            "idx_services_featured_status", ["is_featured", "status"], unique=False
        )
        batch_op.create_index("idx_services_is_featured", ["is_featured"], unique=False)
        batch_op.create_index("idx_services_price", ["price"], unique=False)
        batch_op.create_index(
            "idx_services_price_created", ["price", "created_at"], unique=False
        )
        batch_op.create_index(
            "idx_services_rating_views", ["average_rating", "views"], unique=False
        )
        batch_op.create_index("idx_services_seller_id", ["seller_id"], unique=False)
        batch_op.create_index(
            "idx_services_seller_status", ["seller_id", "status"], unique=False
        )
        batch_op.create_index(
            "idx_services_service_type", ["service_type"], unique=False
        )
        batch_op.create_index("idx_services_status", ["status"], unique=False)
        batch_op.create_index(
            "idx_services_subscription_id", ["subscription_id"], unique=False
        )
        batch_op.create_index(
            "idx_services_title_trgm",
            ["title"],
            unique=False,
            postgresql_using="gin",
            postgresql_ops={"title": "gin_trgm_ops"},
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "idx_messages_conversation",
            ["sender_id", "receiver_id", "timestamp"],
            unique=False,
        )
        batch_op.create_index(
            "idx_messages_receiver_sender", ["receiver_id", "sender_id"], unique=False
        )
        batch_op.create_index(
            "idx_messages_sender_receiver", ["sender_id", "receiver_id"], unique=False
        )
        batch_op.create_index("idx_messages_timestamp", ["timestamp"], unique=False)
        batch_op.create_index(
            "idx_messages_unread_status", ["receiver_id", "status"], unique=False
        )

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(
            "idx_posts_author_created", ["author_id", "created_at"], unique=False
        )
        batch_op.create_index("idx_posts_author_id", ["author_id"], unique=False)
        batch_op.create_index(
            "idx_posts_content_trgm",
            ["content"],
            unique=False,
            postgresql_using="gin",
            postgresql_ops={"content": "gin_trgm_ops"},
        )
        batch_op.create_index("idx_posts_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            "idx_posts_group_created", ["group_id", "created_at"], unique=False
        )
        batch_op.create_index("idx_posts_group_id", ["group_id"], unique=False)

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("idx_users_city", ["city"], unique=False)
        batch_op.create_index(
            "idx_users_city_country", ["city", "country"], unique=False
        )
        batch_op.create_index("idx_users_country", ["country"], unique=False)
        batch_op.create_index("idx_users_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_users_email", ["email"], unique=True)
        batch_op.create_index(
            "idx_users_featured_until", ["marketplace_featured_until"], unique=False
        )
        batch_op.create_index("idx_users_gender", ["gender"], unique=False)
        batch_op.create_index(
            "idx_users_gender_country", ["gender", "country"], unique=False
        )
        batch_op.create_index("idx_users_is_online", ["is_online"], unique=False)
        batch_op.create_index("idx_users_last_seen", ["last_seen"], unique=False)
        batch_op.create_index(
            "idx_users_marketplace_status",
            ["marketplace_subscription_status", "marketplace_subscription_expires"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("idx_users_marketplace_status")
        batch_op.drop_index("idx_users_last_seen")
        batch_op.drop_index("idx_users_is_online")
        batch_op.drop_index("idx_users_gender_country")
        batch_op.drop_index("idx_users_gender")
        batch_op.drop_index("idx_users_featured_until")
        batch_op.drop_index("idx_users_email")
        batch_op.drop_index("idx_users_created_at")
        batch_op.drop_index("idx_users_country")
        batch_op.drop_index("idx_users_city_country")
        batch_op.drop_index("idx_users_city")

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index("idx_posts_group_id")
        batch_op.drop_index("idx_posts_group_created")
        batch_op.drop_index("idx_posts_created_at")
        batch_op.drop_index(
            "idx_posts_content_trgm",
            postgresql_using="gin",
            postgresql_ops={"content": "gin_trgm_ops"},
        )
        batch_op.drop_index("idx_posts_author_id")
        batch_op.drop_index("idx_posts_author_created")

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("idx_messages_unread_status")
        batch_op.drop_index("idx_messages_timestamp")
        batch_op.drop_index("idx_messages_sender_receiver")
        batch_op.drop_index("idx_messages_receiver_sender")
        batch_op.drop_index("idx_messages_conversation")

    with op.batch_alter_table("marketplace_services", schema=None) as batch_op:
        batch_op.drop_index(
            "idx_services_title_trgm",
            postgresql_using="gin",
            postgresql_ops={"title": "gin_trgm_ops"},
        )
        batch_op.drop_index("idx_services_subscription_id")
        batch_op.drop_index("idx_services_status")
        batch_op.drop_index("idx_services_service_type")
        batch_op.drop_index("idx_services_seller_status")
        batch_op.drop_index("idx_services_seller_id")
        batch_op.drop_index("idx_services_rating_views")
        batch_op.drop_index("idx_services_price_created")
        batch_op.drop_index("idx_services_price")
        batch_op.drop_index("idx_services_is_featured")
        batch_op.drop_index("idx_services_featured_status")
        batch_op.drop_index(
            "idx_services_description_trgm",
            postgresql_using="gin",
            postgresql_ops={"description": "gin_trgm_ops"},
        )
        batch_op.drop_index("idx_services_created_at")
        batch_op.drop_index("idx_services_category_status")
        batch_op.drop_index("idx_services_category_id")

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_index("idx_comments_post_id")
        batch_op.drop_index("idx_comments_post_created")
        batch_op.drop_index("idx_comments_parent_id")
        batch_op.drop_index("idx_comments_created_at")
        batch_op.drop_index("idx_comments_author_post")
        batch_op.drop_index("idx_comments_author_id")

    op.create_table(
        "notification",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("actor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("entity_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "entity_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_read", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name="notification_actor_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="notification_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="notification_pkey"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("idx_notifications_user_unread")
        batch_op.drop_index("idx_notifications_user_id")
        batch_op.drop_index("idx_notifications_type")
        batch_op.drop_index("idx_notifications_is_read")
        batch_op.drop_index("idx_notifications_created_at")
        batch_op.drop_index("idx_notifications_actor_id")

    op.drop_table("notifications")
    # ### end Alembic commands ###
