"""Fix blocked users table

Revision ID: 6c637b4ac39c
Revises: 83fb5520853a
Create Date: 2025-11-10 16:57:24.427509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c637b4ac39c'
down_revision = '83fb5520853a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_blocks',
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_user_block')
    )
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_request'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_request'), ['sender_id', 'receiver_id'], postgresql_nulls_not_distinct=False)

    op.drop_table('user_blocks')
    # ### end Alembic commands ###
