"""subbbb

Revision ID: 6ca5dceeefd5
Revises: 953e36e3bcbd
Create Date: 2025-12-04 13:01:22.600863

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ca5dceeefd5"
down_revision = "953e36e3bcbd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("marketplace_services", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("expiry_reminder_sent", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("welcome_email_sent", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(sa.Column("ranking_score", sa.Float(), nullable=True))

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_featured_seller", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("receive_promotional_emails", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("receive_subscription_reminders", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("receive_subscription_reminders")
        batch_op.drop_column("receive_promotional_emails")
        batch_op.drop_column("is_featured_seller")

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    with op.batch_alter_table("marketplace_services", schema=None) as batch_op:
        batch_op.drop_column("ranking_score")
        batch_op.drop_column("welcome_email_sent")
        batch_op.drop_column("expiry_reminder_sent")

    # ### end Alembic commands ###
