"""Change image column to Text type

Revision ID: 6f3e0c7087bb
Revises: 3a2cd6c6fdec
Create Date: 2025-11-18 09:18:06.461242

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f3e0c7087bb"
down_revision = "3a2cd6c6fdec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ad_campaigns", schema=None) as batch_op:
        batch_op.alter_column(
            "image",
            existing_type=sa.VARCHAR(length=500),
            type_=sa.Text(),
            existing_nullable=True,
        )

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    with op.batch_alter_table("ad_campaigns", schema=None) as batch_op:
        batch_op.alter_column(
            "image",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=500),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
