"""working on matchmake

Revision ID: 74c99d75b1aa
Revises: 8ef400feaca0
Create Date: 2026-01-02 16:18:46.372979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c99d75b1aa'
down_revision = '8ef400feaca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchmaking_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('partner_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('partner_city', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('matchmaking_requests', schema=None) as batch_op:
        batch_op.drop_column('partner_city')
        batch_op.drop_column('partner_state')
        batch_op.drop_column('partner_country')

    # ### end Alembic commands ###
