"""empty message

Revision ID: 7a29689b4f6e
Revises: 130574b8cd10
Create Date: 2025-11-11 15:33:24.934617

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7a29689b4f6e"
down_revision = "130574b8cd10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_blocks")
    with op.batch_alter_table("blocked_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))

    with op.batch_alter_table("friend_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("friend_requests", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("blocked_users", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    op.create_table(
        "user_blocks",
        sa.Column("blocker_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("blocked_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["blocked_id"], ["users.id"], name=op.f("user_blocks_blocked_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["blocker_id"], ["users.id"], name=op.f("user_blocks_blocker_id_fkey")
        ),
        sa.PrimaryKeyConstraint("blocker_id", "blocked_id", name=op.f("uq_user_block")),
    )
    # ### end Alembic commands ###
