"""empty message

Revision ID: 7cd714eaed6f
Revises: 2bac31c5643a
Create Date: 2025-11-12 14:25:50.244104

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7cd714eaed6f"
down_revision = "2bac31c5643a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    # ### end Alembic commands ###
