"""empty message

Revision ID: 8b35bd82ac26
Revises: 7a29689b4f6e
Create Date: 2025-11-11 15:50:18.482638

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8b35bd82ac26"
down_revision = "7a29689b4f6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_blocks",
        sa.Column("blocker_id", sa.Integer(), nullable=False),
        sa.Column("blocked_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["blocked_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["blocker_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("blocker_id", "blocked_id"),
        sa.UniqueConstraint("blocker_id", "blocked_id", name="uq_user_block"),
    )
    with op.batch_alter_table("blocked_users", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("friend_requests", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("friend_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
            )
        )

    with op.batch_alter_table("blocked_users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
            )
        )

    op.drop_table("user_blocks")
    # ### end Alembic commands ###
