"""Add birthday notifications

Revision ID: 8da63451d27b
Revises: e9767befcbe9
Create Date: 2026-01-11 09:13:40.900585

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8da63451d27b"
down_revision = "e9767befcbe9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "birthday_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("birthday_user_id", sa.Integer(), nullable=False),
        sa.Column("birthday_date", sa.Date(), nullable=False),
        sa.Column("is_seen", sa.Boolean(), nullable=True),
        sa.Column("is_wished", sa.Boolean(), nullable=True),
        sa.Column("wish_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("wished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["birthday_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("birthday_notifications")
    # ### end Alembic commands ###
