"""added new fields

Revision ID: 90a4f5e6a01a
Revises: a5ed8a05174e
Create Date: 2026-01-25 10:52:19.081174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a4f5e6a01a'
down_revision = 'a5ed8a05174e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('target_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('target_city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.drop_column('target_city')
        batch_op.drop_column('target_state')
        batch_op.drop_column('target_country')

    # ### end Alembic commands ###
