"""sub

Revision ID: 953e36e3bcbd
Revises: cf3607d5159e
Create Date: 2025-12-04 12:51:03.078561

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "953e36e3bcbd"
down_revision = "cf3607d5159e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "marketplace_subscription_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("price_ngn", sa.Float(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("features", sa.Text(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=True),
        sa.Column("max_services", sa.Integer(), nullable=True),
        sa.Column("priority_visibility", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("marketplace_subscription_id", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "marketplace_subscription_status", sa.String(length=20), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("marketplace_subscription_expires", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "marketplace_subscription_tier", sa.String(length=50), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("marketplace_featured_until", sa.DateTime(), nullable=True)
        )
        batch_op.create_foreign_key(
            None, "marketplace_subscriptions", ["marketplace_subscription_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("marketplace_featured_until")
        batch_op.drop_column("marketplace_subscription_tier")
        batch_op.drop_column("marketplace_subscription_expires")
        batch_op.drop_column("marketplace_subscription_status")
        batch_op.drop_column("marketplace_subscription_id")

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    op.drop_table("marketplace_subscription_plans")
    # ### end Alembic commands ###
