"""Increase phone number length

Revision ID: 96b69a282702
Revises: ffebab90cf29
Create Date: 2025-12-17 16:05:16.637578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b69a282702'
down_revision = 'ffebab90cf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('rating_1', sa.Integer(), nullable=True),
    sa.Column('rating_2', sa.Integer(), nullable=True),
    sa.Column('rating_3', sa.Integer(), nullable=True),
    sa.Column('rating_4', sa.Integer(), nullable=True),
    sa.Column('rating_5', sa.Integer(), nullable=True),
    sa.Column('communication_rating', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id')
    )
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_friend_requests_receiver_id')
        batch_op.drop_index('idx_friend_requests_sender_id')

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index('idx_group_members_group_id')
        batch_op.drop_index('idx_group_members_user_id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index('idx_groups_is_active')

    with op.batch_alter_table('marketplace_services', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('whatsapp_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_receiver_id')
        batch_op.drop_index('idx_messages_sender_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_sender_id', ['sender_id'], unique=False)
        batch_op.create_index('idx_messages_receiver_id', ['receiver_id'], unique=False)

    with op.batch_alter_table('marketplace_services', schema=None) as batch_op:
        batch_op.alter_column('whatsapp_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index('idx_groups_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index('idx_group_members_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_group_members_group_id', ['group_id'], unique=False)

    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.create_index('idx_friend_requests_sender_id', ['sender_id'], unique=False)
        batch_op.create_index('idx_friend_requests_receiver_id', ['receiver_id'], unique=False)

    op.drop_table('seller_ratings')
    # ### end Alembic commands ###
