"""Add Donation model

Revision ID: 98a016525660
Revises: 2f4a6d9e8c11
Create Date: 2026-07-27 16:04:57.189963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a016525660'
down_revision = '2f4a6d9e8c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gateway_reference', sa.String(length=100), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_reference')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('ix_cities_country_id')
        batch_op.drop_index('ix_cities_state_id')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_constraint('countries_name_key', type_='unique')

    with op.batch_alter_table('marketplace_services', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('matchmaking_requests', schema=None) as batch_op:
        batch_op.drop_column('images')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_posts_public_id')

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_index('ix_states_country_id')

    # Removed user_blocks uq constraint that caused failure
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_public_id', ['public_id'], unique=True)

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_block', type_='unique')

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_index('ix_states_country_id', ['country_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('ix_posts_public_id', ['public_id'], unique=True)

    with op.batch_alter_table('matchmaking_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('marketplace_services', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_unique_constraint('countries_name_key', ['name'])

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index('ix_cities_state_id', ['state_id'], unique=False)
        batch_op.create_index('ix_cities_country_id', ['country_id'], unique=False)

    op.drop_table('donations')
    # ### end Alembic commands ###
