"""Add daily_budget to AdCampaign

Revision ID: 9cc2e2c30a99
Revises: c3b9bd1c91e4
Create Date: 2025-11-24 20:44:09.982534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc2e2c30a99'
down_revision = 'c3b9bd1c91e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_budget', sa.Float(), nullable=False, server_default='0'))

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_block', type_='unique')

    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.drop_column('daily_budget')

    # ### end Alembic commands ###
