"""empty message

Revision ID: a43ee5c3069f
Revises: ab3d75d78494
Create Date: 2025-11-16 10:35:21.221676

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a43ee5c3069f"
down_revision = "ab3d75d78494"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("reaction_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "post_id", name="unique_user_post_reaction"),
    )
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("comment_post_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(None, "posts", ["post_id"], ["id"])

    with op.batch_alter_table("like", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("like_post_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(None, "posts", ["post_id"], ["id"])

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_posts_id"))

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_posts_id"), ["id"], unique=False)

    with op.batch_alter_table("like", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("like_post_id_fkey"),
            "posts",
            ["post_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("comment_post_id_fkey"),
            "posts",
            ["post_id"],
            ["id"],
            ondelete="CASCADE",
        )

    op.drop_table("reactions")
    # ### end Alembic commands ###
