"""made share functionality

Revision ID: a5ed8a05174e
Revises: 13fe2b08236b
Create Date: 2026-01-23 17:11:31.854663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ed8a05174e'
down_revision = '13fe2b08236b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('share_type', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'posts', ['shared_post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('share_type')
        batch_op.drop_column('shared_post_id')

    # ### end Alembic commands ###
