"""empty message

Revision ID: ab3d75d78494
Revises: a8abdc51a5a5
Create Date: 2025-11-16 10:27:01.667807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab3d75d78494'
down_revision = 'a8abdc51a5a5'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Rename old table 'post' → 'posts'
    op.rename_table('post', 'posts')

    # Step 2: Fix foreign key in 'comment' table
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            'comment_post_id_fkey',  # same name is fine
            'posts',
            ['post_id'],
            ['id'],
            ondelete='CASCADE'
        )

    # Step 3: Fix foreign key in 'like' table
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('like_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            'like_post_id_fkey',
            'posts',
            ['post_id'],
            ['id'],
            ondelete='CASCADE'
        )

    # Optional: Rebuild indexes if needed
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_block', type_='unique')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('like_post_id_fkey'), 'post', ['post_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_post_id_fkey'), 'post', ['post_id'], ['id'])

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('video', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('post_author_id_fkey')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('post_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('post_pkey'))
    )
    op.drop_table('reactions')
    op.drop_table('posts')
    # ### end Alembic commands ###
