"""empty message

Revision ID: aeed8122db93
Revises: 96b69a282702
Create Date: 2025-12-27 09:55:44.454186

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aeed8122db93"
down_revision = "96b69a282702"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("emoji_data", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_column("emoji_data")

    # ### end Alembic commands ###
