"""empty message

Revision ID: b057383e0bf9
Revises: 7ddde86c917c
Create Date: 2025-11-13 22:37:48.278800

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b057383e0bf9"
down_revision = "7ddde86c917c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_members")
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("groups_created_by_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "users", ["created_by"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("groups_created_by_fkey"), "users", ["created_by"], ["id"]
        )

    op.create_table(
        "group_members",
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "joined_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("is_moderator", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("group_members_group_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("group_members_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", name=op.f("group_members_pkey")),
    )
    # ### end Alembic commands ###
