"""mig

Revision ID: c30f592bf05c
Revises: 46f183175e71
Create Date: 2025-11-27 16:34:29.937550

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c30f592bf05c"
down_revision = "46f183175e71"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("matchmaking_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("payment_transaction_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            None, "payment_transactions", ["payment_transaction_id"], ["id"]
        )
        batch_op.drop_column("payment_id")

    with op.batch_alter_table("payment_transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("matchmaking_request_id", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("ad_campaign_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("gateway_reference", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("transaction_type", sa.String(length=20), nullable=True)
        )
        batch_op.drop_constraint(
            batch_op.f("payment_transactions_campaign_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "matchmaking_requests", ["matchmaking_request_id"], ["id"]
        )
        batch_op.create_foreign_key(None, "ad_campaigns", ["ad_campaign_id"], ["id"])
        batch_op.drop_column("campaign_id")

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    with op.batch_alter_table("payment_transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("campaign_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("payment_transactions_campaign_id_fkey"),
            "ad_campaigns",
            ["campaign_id"],
            ["id"],
        )
        batch_op.drop_column("transaction_type")
        batch_op.drop_column("gateway_reference")
        batch_op.drop_column("ad_campaign_id")
        batch_op.drop_column("matchmaking_request_id")

    with op.batch_alter_table("matchmaking_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "payment_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("payment_transaction_id")

    # ### end Alembic commands ###
