"""new

Revision ID: c3b9bd1c91e4
Revises: 413fddaabe53
Create Date: 2025-11-24 17:03:56.228299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b9bd1c91e4'
down_revision = '413fddaabe53'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        # STEP 1 — allow NULL temporarily
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiry_notification_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_renew', sa.Boolean(), nullable=True))

    # STEP 2 — set default value for existing rows
    op.execute("UPDATE ad_campaigns SET duration_days = 7 WHERE duration_days IS NULL")

    # STEP 3 — make it NOT NULL after DB has valid data
    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.alter_column('duration_days', nullable=False)

    # remove dropped fields / constraints
    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ad_campaigns_package_id_fkey'), type_='foreignkey')
        batch_op.drop_column('target_audience')
        batch_op.drop_column('package_id')
        batch_op.drop_column('target_interests')
        batch_op.drop_column('target_countries')

    # new unique constraint
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_block', type_='unique')

    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_countries', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('target_interests', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('target_audience', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('ad_campaigns_package_id_fkey'), 'ad_packages', ['package_id'], ['id'])
        batch_op.drop_column('auto_renew')
        batch_op.drop_column('expiry_notification_sent')
        batch_op.drop_column('duration_days')

    # ### end Alembic commands ###
