"""cloud

Revision ID: cf3607d5159e
Revises: f8a2fff38373
Create Date: 2025-12-03 19:32:40.954807

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf3607d5159e"
down_revision = "f8a2fff38373"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # First, clean up existing file_size data before altering the column
    # This handles cases where file_size might contain non-numeric values
    op.execute(
        """
        UPDATE marketplace_services 
        SET file_size = NULL 
        WHERE file_size IS NOT NULL AND file_size !~ '^[0-9]+$'
    """
    )

    # Also handle empty strings
    op.execute(
        """
        UPDATE marketplace_services 
        SET file_size = NULL 
        WHERE file_size IS NOT NULL AND TRIM(file_size) = ''
    """
    )

    with op.batch_alter_table("marketplace_services", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("file_name", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("cloudinary_public_id", sa.String(length=255), nullable=True)
        )

        # Now safely alter the column with explicit conversion
        batch_op.alter_column(
            "file_size",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using="file_size::integer",
        )

        batch_op.alter_column(
            "file_type",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=100),
            existing_nullable=True,
        )

    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_blocks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_block", type_="unique")

    with op.batch_alter_table("marketplace_services", schema=None) as batch_op:
        batch_op.alter_column(
            "file_type",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "file_size",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
        )
        batch_op.drop_column("cloudinary_public_id")
        batch_op.drop_column("file_name")

    # ### end Alembic commands ###
