"""empty message

Revision ID: d8f82197532f
Revises: e35e0a7a9ae4
Create Date: 2025-11-09 23:04:39.081377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f82197532f'
down_revision = 'e35e0a7a9ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_pic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('marital_status')
        batch_op.drop_column('bio')
        batch_op.drop_column('cover_pic')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
