"""ad

Revision ID: e6b627359ec7
Revises: 9cc2e2c30a99
Create Date: 2025-11-25 11:36:27.561332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b627359ec7'
down_revision = '9cc2e2c30a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_gender', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_age_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_age_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_countries', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_occupation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_relationship', sa.Text(), nullable=True))

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_block', type_='unique')

    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.drop_column('target_relationship')
        batch_op.drop_column('target_occupation')
        batch_op.drop_column('target_education')
        batch_op.drop_column('target_interests')
        batch_op.drop_column('target_countries')
        batch_op.drop_column('target_age_max')
        batch_op.drop_column('target_age_min')
        batch_op.drop_column('target_gender')

    # ### end Alembic commands ###
