"""one  migration

Revision ID: ef8960883a24
Revises: 55b2bc8530f6
Create Date: 2025-11-18 13:02:16.118983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8960883a24'
down_revision = '55b2bc8530f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impressions', sa.Integer(), nullable=True))
        batch_op.drop_column('max_impressions')

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_block', type_='unique')

    with op.batch_alter_table('ad_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_impressions', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('impressions')

    # ### end Alembic commands ###
