"""earn

Revision ID: f08a385af010
Revises: f4f70d915dac
Create Date: 2025-12-02 22:13:08.094428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08a385af010'
down_revision = 'f4f70d915dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earnings', sa.Float(), nullable=True))

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_user_block', ['blocker_id', 'blocked_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_block', type_='unique')

    with op.batch_alter_table('marketplace_services', schema=None) as batch_op:
        batch_op.drop_column('earnings')

    # ### end Alembic commands ###
