"""add activity logs

Revision ID: f19c61faee54
Revises: b8c1a3d4e5f6
Create Date: 2026-03-18 10:12:08.254827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19c61faee54'
down_revision = 'b8c1a3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_authenticated', sa.Boolean(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index('idx_activity_country', ['country'], unique=False)
        batch_op.create_index('idx_activity_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_activity_event_type', ['event_type'], unique=False)
        batch_op.create_index('idx_activity_ip', ['ip_address'], unique=False)
        batch_op.create_index('idx_activity_path', ['path'], unique=False)
        batch_op.create_index('idx_activity_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_user_id')
        batch_op.drop_index('idx_activity_path')
        batch_op.drop_index('idx_activity_ip')
        batch_op.drop_index('idx_activity_event_type')
        batch_op.drop_index('idx_activity_created_at')
        batch_op.drop_index('idx_activity_country')

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
