"""new table2

Revision ID: ffebab90cf29
Revises: d55b810ddd3d
Create Date: 2025-12-16 09:24:55.369293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffebab90cf29'
down_revision = 'd55b810ddd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('review_images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_reviews', schema=None) as batch_op:
        batch_op.drop_column('review_images')
        batch_op.drop_column('review_type')

    # ### end Alembic commands ###
